# Generated by Django 5.1.2 on 2024-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0004_alter_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='media/recipes_img'),
        ),
    ]
