# Generated by Django 5.1.2 on 2024-11-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0008_remove_recipe_ingridients_product_recipeingredient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
    ]
