# Generated by Django 5.1.2 on 2024-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0009_alter_recipeingredient_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_calories',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
