# Generated by Django 5.1.2 on 2024-11-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0010_recipe_recipe_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
