# Generated by Django 5.1.2 on 2024-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0011_alter_recipe_recipe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_fats',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_proteins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
