# Generated by Django 5.1.2 on 2024-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0012_recipe_recipe_carbohydrates_recipe_recipe_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Гр', 'Гр'), ('Мл', 'Мл'), ('Ч.л', 'Ч.л'), ('С.л', 'С.л'), ('Шт', 'Шт'), ('По вкусу', 'По вкусу')], max_length=8),
        ),
    ]
