# Generated by Django 5.1.2 on 2024-11-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0013_alter_recipeingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_steps',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipiesapp.product'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_steps', to='recipiesapp.recipe')),
            ],
        ),
    ]
