# Generated by Django 5.1.2 on 2024-11-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0015_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
