# Generated by Django 5.1.2 on 2024-11-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiesapp', '0016_alter_product_calories_alter_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_text',
            field=models.CharField(default='По умолчанию', max_length=20),
            preserve_default=False,
        ),
    ]
